### ISSUE TITLE
New open work related

### ISSUE THREAD

**Issue by Liming-Cheng** [yan99033/monodepth-cpp#12]
Hi ! yan, recently I found an efficent work like monodepth, and unfortunately it was implemented by python and pytorch.  So it cannot  be used in slam easily.
Here is the link: https://github.com/JiawangBian/SC-SfMLearner-Release
To implement it by c++, libtorcch must be  compiled and the model .th  be converted to .pt, and all of this  maybe simple, but what is difficult is to convert the python code to c++.  
You have implemented monodepth by c++ , so lt will be a great contribution to this filed if you have interest in implementing the work in c++. I hope sincerely you can consider it when you are not busy , thank you!
Good luck for everything!

**Comment by yan99033** [comment]
Recently I have been dabbling in PyTorch Python training code. I think, in general, the inference code should be very similar to what I did in Monodepth-cpp: 1. load the network, 2. define input and output layers, 3. feed the input, and 4. get the output.
Unfortunately, I am quite busy with my research lately. However, I will keep this issue open so that other people can come in and get in touch with you.

**Comment by yan99033** [comment]
Hi @Liming-Cheng, check out the repo that I released, [MiDaS-cpp](https://github.com/yan99033/MiDaS-cpp), a project that runs depth prediction in PyTorch c++. Hope that helps.
